### PR TITLE
chore: release 1.85.0

### PR DESCRIPTION
**Pull request by ajbt200128**

### CODE REVIEW

**Comment by kopecs** [comment]
I believe you have to update `.pre-commit-config.yaml` too (not a huge fan of the current CI config, if you want to update it :) ). And you'll need to tag after merge.

**Review by kopecs — APPROVED** [review]
lgtm once you update the other file

**Comment by ajbt200128** [comment]
@kopecs release process says to bump the pre-commit config file after the tag has been created, and to create the tag after this PR has been merged (See Semgrep Release/Rollback process). I wanted to update the file here first too, but it seems that no one else has done that, so I'm not sure if there's an issue with it.

See: 
https://github.com/semgrep/pre-commit/pull/17
https://github.com/semgrep/pre-commit/pull/18

**Comment by kopecs** [comment]
You can have it point at the HEAD commit on this branch instead of the tag, so we can actually test before the tag goes live, which is a fundamental flaw imo with what's happened previously. If you want to just do it that way too that's fine I guess, but somewhat (not fully) defeats the point of testing.

**Pull request merged**
