### PR TITLE
chore: release 1.77.0 and 1.78.0

### PR DESCRIPTION
**Pull request by amchiclet**
* [x] tag(s) created post-merge (this PR has 2 commits)

### CODE REVIEW

**Comment by kopecs** [comment]
We can do 1.78.0 in this one as well if you want (with a rebase merge).

**Comment by amchiclet** [comment]
Yes, I'll commit 1.78.0 on this PR too. Thanks!

**Review by kopecs — APPROVED** [review]
lgtm just do a rebase merge

**Comment by kopecs** [comment]
Oh it seems like the workflow from #9 may be annoying. Given we now have to (1) update the CI job tag reference; (2) create the tags for these; (3) manually run it (Since it has a dependency on the tags being created).

**Comment by amchiclet** [comment]
So true. I was thinking we need to create tags first, then update the CI job tag. I wanna automate this if possible.

**Comment by kopecs** [comment]
Ideally CI doesn't need a tag IMO, and it can just do it on what is present at that version. Agree for sure about automating.

**Pull request merged**
